import 'reflect-metadata';
import { DataSource } from 'typeorm';
import { hash } from 'bcrypt';
import { AuditLog, Correspondence, CorrespondenceAttachment, CorrespondenceComment, ExternalLink, InstitutionalForm, News, Procedure, ProcedureStep, RepositoryDocument, Role, RoleName, User } from './entities';

const ds=new DataSource({type:'postgres',host:process.env.DB_HOST||'localhost',port:+(process.env.DB_PORT||5432),username:process.env.DB_USER||'sgip',password:process.env.DB_PASSWORD||'sgip',database:process.env.DB_NAME||'sgip',entities:[Role,User,Correspondence,CorrespondenceAttachment,CorrespondenceComment,RepositoryDocument,Procedure,ProcedureStep,InstitutionalForm,ExternalLink,News,AuditLog],synchronize:true});
(async()=>{await ds.initialize(); const rr=ds.getRepository(Role); for(const name of [RoleName.ADMIN,RoleName.EDITOR,RoleName.CONSULTOR]) if(!await rr.findOne({where:{name}})) await rr.save(rr.create({name,description:name}));
 const ur=ds.getRepository(User); async function user(name,email,password,position,roleName){let u=await ur.findOne({where:{email}}); if(!u){u=ur.create({name,email,passwordHash:await hash(password,10),position,roles:[await rr.findOne({where:{name:roleName}})]}); await ur.save(u);} return u;}
 const admin=await user('Keylor Herrera','admin@itcr.ac.cr','Admin123!','Administrador',RoleName.ADMIN); const editor=await user('Ana Torres','editor@itcr.ac.cr','Editor123!','Coordinadora',RoleName.EDITOR); const consult=await user('Carlos Ruiz','consulta@itcr.ac.cr','Consulta123!','Funcionario',RoleName.CONSULTOR);
 const link=ds.getRepository(ExternalLink); if(await link.count()===0) await link.save([
  {name:'Sistema de solicitudes',url:'https://www.tec.ac.cr/',description:'Solicitudes institucionales',category:'Administrativo'},
  {name:'SICOP',url:'https://www.sicop.go.cr/',description:'Compras públicas',category:'Compras'},
  {name:'Correo institucional',url:'https://outlook.office.com/',description:'Correo TEC',category:'Comunicación'},
  {name:'SharePoint',url:'https://www.microsoft.com/microsoft-365/sharepoint/collaboration',description:'Documentos y colaboración',category:'Comunicación'},
  {name:'TEC Digital',url:'https://tecdigital.tec.ac.cr/',description:'Servicios académicos para profesores',category:'Académico'},
  {name:'Biblioteca',url:'https://www.tec.ac.cr/biblioteca',description:'Recursos de biblioteca',category:'Académico'}
 ] as any);
 const proc=ds.getRepository(Procedure); if(await proc.count()===0) await proc.save(proc.create({code:'SG-PR-01',name:'Solicitud de transporte',description:'Proceso para solicitar transporte institucional.',category:'Servicios Generales',status:'Activo',responsibleArea:'Servicios Generales',requirements:['Completar formulario','Indicar fechas y destino','Contar con aprobación de jefatura'],steps:[{stepOrder:1,title:'Completar formulario',description:'Descargar y completar el formulario.'},{stepOrder:2,title:'Solicitar aprobación',description:'Obtener aprobación de la jefatura.'},{stepOrder:3,title:'Enviar solicitud',description:'Remitir a Servicios Generales.'}] as any,links:[{label:'Sistema de solicitudes',url:'https://www.tec.ac.cr/'}],relatedForms:[{label:'Solicitud de transporte'}]}));
 const docs=ds.getRepository(RepositoryDocument); if(await docs.count()===0) await docs.save([{name:'Reglamento académico del TEC',type:'Reglamento',category:'Reglamentos',description:'Reglamento académico institucional',version:'1.0',status:'ACTIVO',responsible:editor},{name:'Guía de matrícula',type:'Guía',category:'Guías',description:'Pasos y requisitos para matrícula',version:'1.0',status:'ACTIVO',responsible:editor}] as any);
 const forms=ds.getRepository(InstitutionalForm); if(await forms.count()===0) await forms.save([{name:'Formulario de viáticos',description:'Solicitud de viáticos',category:'Finanzas',format:'PDF',createdBy:editor,updatedBy:editor},{name:'Solicitud de transporte',description:'Solicitud de transporte institucional',category:'Servicios Generales',format:'PDF',createdBy:editor,updatedBy:editor}] as any);
 const news=ds.getRepository(News); if(await news.count()===0) await news.save([{title:'Actividad cultural en el campus',summary:'Actividad cultural para la comunidad.',content:'Información de ejemplo.',category:'Eventos',author:editor,published:true}] as any);
 const corr=ds.getRepository(Correspondence); if(await corr.count()===0) await corr.save(corr.create({code:'COR-2026-001',subject:'Revisión Convenio Alianza Francesa',description:'Revisar documentos adjuntos y emitir observaciones.',type:'Comunicación externa',priority:'MEDIA',status:'EN_REVISION' as any,sender:admin,responsible:editor,participants:[admin,editor],dueDate:new Date(Date.now()+7*86400000)}));
 console.log('Seed completado'); await ds.destroy();})().catch(e=>{console.error(e);process.exit(1)});
